name: noop_benchmark_depth_50
pipelines:
- name: NoOp Chain Depth 50
  inputs:
  - 0
  outputs:
  - 49
  dataset_stage_id: 0
  loadgen:
    component: loadgen.OfflineLoadScheduler
    queue_depth: 100
    max_queries: 10
    timeout: 60000
    config:
      rate: 0
  stages:
  - name: Identity Stage 0
    id: 0
    component: stages.stage.Stage
    outputs:
    - 1
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 1
    id: 1
    component: stages.stage.Stage
    outputs:
    - 2
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 2
    id: 2
    component: stages.stage.Stage
    outputs:
    - 3
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 3
    id: 3
    component: stages.stage.Stage
    outputs:
    - 4
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 4
    id: 4
    component: stages.stage.Stage
    outputs:
    - 5
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 5
    id: 5
    component: stages.stage.Stage
    outputs:
    - 6
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 6
    id: 6
    component: stages.stage.Stage
    outputs:
    - 7
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 7
    id: 7
    component: stages.stage.Stage
    outputs:
    - 8
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 8
    id: 8
    component: stages.stage.Stage
    outputs:
    - 9
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 9
    id: 9
    component: stages.stage.Stage
    outputs:
    - 10
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 10
    id: 10
    component: stages.stage.Stage
    outputs:
    - 11
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 11
    id: 11
    component: stages.stage.Stage
    outputs:
    - 12
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 12
    id: 12
    component: stages.stage.Stage
    outputs:
    - 13
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 13
    id: 13
    component: stages.stage.Stage
    outputs:
    - 14
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 14
    id: 14
    component: stages.stage.Stage
    outputs:
    - 15
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 15
    id: 15
    component: stages.stage.Stage
    outputs:
    - 16
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 16
    id: 16
    component: stages.stage.Stage
    outputs:
    - 17
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 17
    id: 17
    component: stages.stage.Stage
    outputs:
    - 18
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 18
    id: 18
    component: stages.stage.Stage
    outputs:
    - 19
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 19
    id: 19
    component: stages.stage.Stage
    outputs:
    - 20
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 20
    id: 20
    component: stages.stage.Stage
    outputs:
    - 21
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 21
    id: 21
    component: stages.stage.Stage
    outputs:
    - 22
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 22
    id: 22
    component: stages.stage.Stage
    outputs:
    - 23
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 23
    id: 23
    component: stages.stage.Stage
    outputs:
    - 24
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 24
    id: 24
    component: stages.stage.Stage
    outputs:
    - 25
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 25
    id: 25
    component: stages.stage.Stage
    outputs:
    - 26
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 26
    id: 26
    component: stages.stage.Stage
    outputs:
    - 27
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 27
    id: 27
    component: stages.stage.Stage
    outputs:
    - 28
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 28
    id: 28
    component: stages.stage.Stage
    outputs:
    - 29
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 29
    id: 29
    component: stages.stage.Stage
    outputs:
    - 30
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 30
    id: 30
    component: stages.stage.Stage
    outputs:
    - 31
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 31
    id: 31
    component: stages.stage.Stage
    outputs:
    - 32
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 32
    id: 32
    component: stages.stage.Stage
    outputs:
    - 33
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 33
    id: 33
    component: stages.stage.Stage
    outputs:
    - 34
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 34
    id: 34
    component: stages.stage.Stage
    outputs:
    - 35
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 35
    id: 35
    component: stages.stage.Stage
    outputs:
    - 36
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 36
    id: 36
    component: stages.stage.Stage
    outputs:
    - 37
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 37
    id: 37
    component: stages.stage.Stage
    outputs:
    - 38
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 38
    id: 38
    component: stages.stage.Stage
    outputs:
    - 39
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 39
    id: 39
    component: stages.stage.Stage
    outputs:
    - 40
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 40
    id: 40
    component: stages.stage.Stage
    outputs:
    - 41
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 41
    id: 41
    component: stages.stage.Stage
    outputs:
    - 42
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 42
    id: 42
    component: stages.stage.Stage
    outputs:
    - 43
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 43
    id: 43
    component: stages.stage.Stage
    outputs:
    - 44
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 44
    id: 44
    component: stages.stage.Stage
    outputs:
    - 45
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 45
    id: 45
    component: stages.stage.Stage
    outputs:
    - 46
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 46
    id: 46
    component: stages.stage.Stage
    outputs:
    - 47
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 47
    id: 47
    component: stages.stage.Stage
    outputs:
    - 48
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 48
    id: 48
    component: stages.stage.Stage
    outputs:
    - 49
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
  - name: Identity Stage 49
    id: 49
    component: stages.stage.Stage
    outputs: []
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
