name: noop_benchmark_depth_1
pipelines:
- name: NoOp Chain Depth 1
  inputs:
  - 0
  outputs:
  - 0
  dataset_stage_id: 0
  loadgen:
    component: loadgen.OfflineLoadScheduler
    queue_depth: 100
    max_queries: 10
    timeout: 60000
    config:
      rate: 0 # Unlimited rate for offline scheduler
  stages:
  - name: Identity Stage 0
    id: 0
    component: stages.stage.Stage
    outputs: []
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
