name: noop_benchmark_depth_10_size_1048576_mode_copy
pipelines:
- name: NoOp Chain Depth 10 Size 1048576 Mode copy
  inputs:
  - 0
  outputs:
  - 9
  dataset_stage_id: 0
  loadgen:
    component: loadgen.OfflineLoadScheduler
    queue_depth: 100
    max_queries: 10
    timeout: 60000
    config:
      rate: 0
  stages:
  - name: Copy Stage 0
    id: 0
    component: stages.evaluation.data_injector.DataInjector
    outputs:
    - 1
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config:
      payload_size: 1048576
  - name: Copy Stage 1
    id: 1
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 2
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 2
    id: 2
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 3
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 3
    id: 3
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 4
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 4
    id: 4
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 5
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 5
    id: 5
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 6
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 6
    id: 6
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 7
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 7
    id: 7
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 8
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 8
    id: 8
    component: stages.evaluation.copy_stage.CopyStage
    outputs:
    - 9
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
  - name: Copy Stage 9
    id: 9
    component: stages.evaluation.copy_stage.CopyStage
    outputs: []
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
